package com.chrynan.presentation.compose

import androidx.compose.runtime.Composable
import androidx.compose.runtime.currentCompositeKeyHash

// key is the one provided by the user or the one generated by the compose runtime
@Composable
internal fun getNonNullKey(providedKey: Any?): Any =
    if (providedKey == null || (providedKey is String && providedKey.isEmpty())) {
        currentCompositeKeyHash.toString(36)
    } else {
        providedKey
    }
